import "./globals.css";
import Context from "@/Helper/Context";

export const metadata={
  title:'My App',
  description:'Generated By Next.js and React'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning> 
        <Context>
          {children}
        </Context>
      </body>
    </html>
  );
}
